name: Tests

on:
  push:
    branches: [master]
  pull_request: 
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-20.04
    container:
      image: faasm/toolchain:0.0.1
    steps:
      - name: "Build wasi-libc"
        run: >
          cmake
          -GNinja
          -DCMAKE_BUILD_TYPE=Release
          ..
        working-directory: build
      - name: "Build tests"
        run: cmake --build . --target faabric_tests
        working-directory: build
      # --- Tests ---
      - name: "Run tests"
        run: ./bin/faabric_tests
        working-directory: build
