name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: "Get the latest code"
        uses: actions/checkout@v2
      - name: "Get LLVM version"
        id: llvm_ver
        run: echo "::set-output name=version::$(cat LLVM_VERSION)"
        shell: bash
      - name: "Print LLVM version"
        run: echo "LLVM VERSION = ${{ steps.llvm_ver.outputs.version }}"
      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v1
      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v1
      - name: "Build the sysroot container"
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          file: docker/sysroot.dockerfile
          build-args: LLVM_VERSION=${{ steps.llvm_ver.outputs.version }}

