name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  checks:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-20.04
    container:
      image: faasm/cpp-sysroot:0.1.6
      options: --user root
    defaults:
      run:
        working-directory: /code/cpp
    steps:
      # --- Update code --
      - name: "Pull forked repo into container"
        run: |
          git remote set-url origin https://github.com/FlowDrucka64/cpp.git
          git fetch origin
          git pull origin main
      - name: "Update Faabric submodule"
        run: git submodule update --init -f third-party/faabric
      - name: "Update FFI submodule"
        run: git submodule update --init -f third-party/libffi
      - name: "Update FFmpeg submodule"
        run: git submodule update --init -f third-party/FFmpeg
      - name: "Update wasi-libc submodule"
        run: git submodule update --init -f third-party/wasi-libc
      - name: "Pull/Update Tensorflow submodule"
        run: git submodule update --init -f third-party/tensorflow
      - name: "Install requirements"
        run: pip3 install -r requirements.txt
      # ---Installing packages required for TF in this hacky way
      - name: "Install packages"
        run: |
         apt update
         apt-get install curl -y
         apt-get install unzip -y
      # --- Build libraries to wasm ---
      - name: "Build libc"
        run: inv libc
      - name: "Build libfaasm"
        run: inv libfaasm
      - name: "Build libfaasmp"
        run: inv libfaasmp
      - name: "Build libfaasmpi"
        run: inv libfaasmpi
      - name: "Build libffi"
        run: inv libffi
      - name: "Build libfake"
        run: inv libfake
      - name: "Build libemscripten"
        run: inv libemscripten
      - name: "Build FFmpeg"
        run: inv ffmpeg
      - name: "Build TFlib"
        run: inv tensorflow.lib
      # --- Build functions to wasm ---
      - name: "Build the functions"
        run: inv func.local --clean
      - name: "Build tf func"
        run: inv tensorflow.func
      # --- Build libraries natively ---
      - name: "Build libfaasm native"
        run: inv libfaasm --native --clean
      - name: "Build libfaasmp native"
        run: inv libfaasmp --native --clean
      - name: "Build libfaasmpi native"
        run: inv libfaasmpi --native --clean
      # --- Formatting ---
      - name: "Check python"
        run: ./bin/check_python.sh
      - name: "Run C/C++ formatting"
        run: ./bin/run_clang_format.sh
      - name: "Check no formatting changes"
        run: git diff --exit-code
